### ISSUE TITLE
No entities appear in Home Assistant

### ISSUE THREAD

**Issue by rohrsh** [tellerbop/havistapool#6]
Hi there

I am trying to get this Home Assistant integration up and running. I enter my username/password and the integration says it has been setup, but it doesn't serve up any devices or entities. 

<img width="661" alt="image" src="https://user-images.githubusercontent.com/38928979/102723618-1b0e3b80-4359-11eb-89dc-2bc4e2afeba0.png">

Is there any debug information I can provide to help learn the problem? 

Thank you

**Comment by tellerbop** [comment]
Sounds strange but could be a glitch or sone changed behavior in HA as I havn’t touched this code in a long while. Let me take a look at this after christmas, I’ll get back to you.

**Comment by barcasmo** [comment]
Hola, a mi me pasa lo mismo, no aparece ningún dispositivo o entidad

**Comment by rohrsh** [comment]
I just noticed this error in my logs which could help you track down the problem:  

`Error setting up entry xxxxxxxxxxxx@yahoo.com for vistapool
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/vistapool/__init__.py", line 103, in async_setup_entry
    return await data.update(utcnow())
  File "/config/custom_components/vistapool/vistapool_account.py", line 130, in update
    self.discover_pools(
  File "/config/custom_components/vistapool/vistapool_account.py", line 84, in discover_pools
    dashboard = Dashboard(
  File "/config/custom_components/vistapool/dashboard.py", line 247, in __init__
    self.instruments = [
  File "/config/custom_components/vistapool/dashboard.py", line 250, in <listcomp>
    if instrument.setup(connection, pool, **config)
  File "/config/custom_components/vistapool/dashboard.py", line 43, in setup
    if not self.is_supported:
  File "/config/custom_components/vistapool/dashboard.py", line 94, in is_supported
    if hasattr(self._pool, supported):
  File "/config/custom_components/vistapool/vistapool_connect_account.py", line 329, in ph_relay_state_supported
    result = parse_int(check)
  File "/config/custom_components/vistapool/util.py", line 30, in parse_int
    return int(val)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'`

**Comment by rohrsh** [comment]
I don't suppose you have had a second to look into this one? I'd be so very thankful.

**Comment by tellerbop** [comment]
> I don't suppose you have had a second to look into this one? I'd be so very thankful.

Unfortunately no. I’ve been Covid-19 sick and need some time before I’m back in full strength. 🥵

**Comment by rohrsh** [comment]
Oh no! I do hope you have had a good recovery. 

I received the email below today. I wonder if this will cause any breaking changes for us all?

> Dear user,
> We are pleased to inform you that with a view to improving access and connectivity services offered by our water treatment, measurement and control equipment, we will soon launch the new Vistapool platform that will replace the current version.
> 
> This new version will have an improved interface and will allow faster access to the control and management of the water parameters and connected equipment of your pool.
> 
> In order to continue using this free service, you need to confirm your information and read, accept and comply with our general conditions of use. But you don't have to worry because on the Vistapool platform itself, once you connect, you will be guided through the complete registration and data collection process.
> 
> The new interface will not be able to display the data history stored on the current server, therefore, in case you want to keep the data history of your installation, we recommend that you download it before migration.
> 
> The date for the start of the new Vistapool platform is scheduled for April 21, 2021. We hope you find it very useful!
> 
> “HAYWARD are the pioneers in low-salinity equipment and currently, with more than 11,000 active connections to our servers, leads the automated smart pool market in Europe.”
> 
> Javier Vinageras
> Director of Business Development of the Hayward Group in Europe
> 
>

**Comment by tellerbop** [comment]
I saw it, I knew it was coming 🙂 Let’s hope they haven’t changed the API too much. We’ll know on Wednesday.
Since I have Hayward equipment myself and I just recently started the pool (it’s seasonal where I live) be sure there will be a fix sooner rather than later. 🙂

**Comment by mutzl** [comment]
Did you have a look, yet?
I tried myself - but without of luck so far.

Getting an access token for my credentials. Also getting SessionId and SID. 
But no luck with the final GET call.

And it's the worst API I have ever seen. 
JSON result for  my pool is around 3800 verbose lines, taking almost one minute (55 seconds!) for download.

**Comment by tellerbop** [comment]
> Did you have a look, yet?
> I tried myself - but without of luck so far.
> 
> Getting an access token for my credentials. Also getting SessionId and SID.
> But no luck with the final GET call.
> 
> And it's the worst API I have ever seen.
> JSON result for my pool is around 3800 verbose lines, taking almost one minute (55 seconds!) for download.

Yes I have. It seems like they have changed to google api and to be honest I've never worked with that one before. Decoding the flow and I'm afraid it's more work than just changing an URL. I'll look into it further tomorrow.

**Comment by mutzl** [comment]
When analyzing the traffic, I wonder where the `AID` and `zx` parameter in the payload come from. 
I guess, that's my missing piece to get the response.

![image](https://user-images.githubusercontent.com/2855185/116391235-30233b80-a81f-11eb-8d5d-50c294048470.png)

**Comment by tellerbop** [comment]
I’ve managed to decode the flow now, however the auth flow needs to be reimplemented and unfortunately the payload also has a different structure. Not a problem but it will take some effort and thorough testing before it will work again.

**Comment by mutzl** [comment]
I'd like to contribute to this project - especially that I need additional functionality myself, like controlling the filtration.
Unfortunately I don't speak any Python.

My "homebase" is C# so I am trying to develop an app with NetDaemon for homeassistant. But I am still stuck at the final step of the auth flow. 

Would you share your findings, please?

Update: Never mind. Solved it myself.

**Comment by tellerbop** [comment]
I’ve been in contact with Hayward and they have promised to share all the details with me to integrate with their API “correctly”. I’m waiting for the details and will start implementing this as soon as I get it.

**Comment by mutzl** [comment]
Thank you for the update, Thomas.
In the meantime, my own dotnet vistapool integration is up and running. I even started to control some parameters, like turning light on and off.

It feels totally wrong, though. When I mimic the traffic from their web client, I receive so much redundant data, it takes almost a minute.
But if you like, I can share my findings anytime.

(I was even considering to totally drop the vistapool wifi module and build my own modbus integration. But I guess, I will wait for your outcome first, before taking this route.)

**Comment by tellerbop** [comment]
> Thank you for the update, Thomas.
> In the meantime, my own dotnet vistapool integration is up and running. I even started to control some parameters, like turning light on and off.
> 
> It feels totally wrong, though. When I mimic the traffic from their web client, I receive so much redundant data, it takes almost a minute.
> But if you like, I can share my findings anytime.
> 
> (I was even considering to totally drop the vistapool wifi module and build my own modbus integration. But I guess, I will wait for your outcome first, before taking this route.)

TBH I think many of the calls they do in their webclient is totally unnecessary for our integration. We basically just want a snapshot of the pool once every 5 minutes or so if not longer intervals + beeing able to control lights and filtering. However the authentication flow looks like it’s based on openId and once you’ve completed  that first step and maintain the session as well as refreshing the JWT token, data retrieval in my tests has been pretty fast.

**Comment by mutzl** [comment]
Hmm. For me, the auth flow turned out to be rather easy. 
But getting the data is a nightmare in 2 steps.

1.)
`POST https://firestore.googleapis.com/google.firestore.v1beta1.Firestore/Listen/channel?database=...`

with body `req0___data__= {"database":...},"targetId":4}}`

2.) 
using SID and gsessionid from the response...
`GET https://firestore.googleapis.com/google.firestore.v1beta1.Firestore/Listen/channel?database=...`

But the second call, which returns the result, takes always more than 55 seconds.

Would be happy, if you point me to a better direction!

**Comment by tellerbop** [comment]
Since firestore is a nosql db you might be better off with using the .NET client rather than trying to mimic REST calls. Imho. https://developers.google.com/api-client-library/dotnet/apis/firestore/v1

There is one for python as well which I’m going to use once I get all the connection details from Hayward.

**Comment by tellerbop** [comment]
Closing this see #9 For latest updates
